### ISSUE TITLE
这个报错是为啥

### ISSUE THREAD

**Issue by Le0f** [XYZliang/AutoZFBXiaoYuanFangYiSign#14]
Traceback (most recent call last):
  File "d:/下载/AutoZFBXiaoYuanFangYiSign-main/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 428, in <module>
    statistics(return_state)
  File "d:/下载/AutoZFBXiaoYuanFangYiSign-main/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 306, in statistics
    message = message + name + " " + str(ID) + " 打卡错误！\n"
TypeError: can only concatenate str (not "NoneType") to str

**Comment by XYZliang** [comment]
应该是你的配置有问题。检查你的配置
