### ISSUE TITLE
Workflow run failed

### ISSUE THREAD

**Issue by dotponder** [XYZliang/AutoZFBXiaoYuanFangYiSign#25]
今日9时收到邮件Workflow run failed。
```
Run python sign.py
Traceback (most recent call last):
  File "/home/runner/work/AutoZFBXiaoYuanFangYiSign/AutoZFBXiaoYuanFangYiSign/sign.py", line 424, in <module>
2022-01-09 01:49:23.009217:19084127开始
    return_state = start(yourID)
  File "/home/runner/work/AutoZFBXiaoYuanFangYiSign/AutoZFBXiaoYuanFangYiSign/sign.py", line 286, in start
    verify_code = verify(cookie)
  File "/home/runner/work/AutoZFBXiaoYuanFangYiSign/AutoZFBXiaoYuanFangYiSign/sign.py", line 110, in verify
    res = opener.open(request)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Error: Process completed with exit code 1.
```

**Comment by 1955782864** [comment]
今天校园防疫升级以后就这样了

**Comment by XYZliang** [comment]
目测是改接口了。放假了最近抽时间我修改一下

**Comment by Barry04** [comment]
找到修改的接口了吗？关键是这个还会显示打卡成功。也不知道是咋回事

**Comment by XYZliang** [comment]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/59312540/148889029-64853aa5-e4f4-422d-ae66-2c7b2e3f7413.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/59312540/148889083-8b12faa1-e243-448e-9440-2307eb268569.png">
我尝试几次后发现一切正常？是否能提供你的配置信息我看看什么情况

**Comment by Barry04** [comment]
> 大佬看看我的仓库，我fork了你的。也出现上面的情况，我本地也不行。GitHub的action也不行

**Comment by Barry04** [comment]
> <img alt="image" width="1205" src="https://user-images.githubusercontent.com/59312540/148889029-64853aa5-e4f4-422d-ae66-2c7b2e3f7413.png">
> 
> <img alt="image" width="1153" src="https://user-images.githubusercontent.com/59312540/148889083-8b12faa1-e243-448e-9440-2307eb268569.png">
> 
> 我尝试几次后发现一切正常？是否能提供你的配置信息我看看什么情况

大佬可以弄一个交流群，交流起来比较方便些。

**Comment by Barry04** [comment]
我好像知道问题所在了，他把国外的ip给拉黑了，我是先用vpn试了打卡不成功，用国内的ip发起请求就可以。可能是支付宝的问题。具体原因我不清楚。

**Comment by XYZliang** [comment]
这个404貌似是配置有问题。我刚在我的新版上用你的配置是完全ok的，一会我提交上来你试试新版
<img width="540" alt="image" src="https://user-images.githubusercontent.com/59312540/148913898-c3460951-4d5b-4de6-8867-4c25f0af295f.png">

**Comment by YANGNIGHT** [comment]
我也是两天前就开始不能正常运行了  也就是现在只能通过腾讯云函数或者国内服务器来实现了吗

**Comment by YANGNIGHT** [comment]
嘿嘿 坐等大佬出新教程

**Comment by XYZliang** [comment]
腾讯云的方案实现了国内用白嫖方法定时签到。新版本和教程已经更新。
