### ISSUE TITLE
出现 'gbk' codec can't decode byte 0xae in position 160: illegal multibyte sequence，是啥原因呀

### ISSUE THREAD

**Issue by ygxiuming** [XYZliang/AutoZFBXiaoYuanFangYiSign#41]

**Comment by ygxiuming** [comment]
我把这个  conf.read("SignConfig.cfg")改成    conf.read("SignConfig.cfg",encoding='utf-8')顺利读取了但是后面获取到的list超出限制，没有数据是啥情况呀！
Traceback (most recent call last):
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 499, in <module>
    DoSign()
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 482, in DoSign
    return_state = start(int(signID))
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 307, in start
    if login() == 'ERROR':
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 122, in login
    if verify(cookie) == True:
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 139, in verify
    if sign_history(cookie=cookie, check_exit=True):
  File "F:/desktop/AutoZFBXiaoYuanFangYiSign-main/sign.py", line 180, in sign_history
    last_dic = res_dic['data']['list'][0]
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/54978922/152642535-06729ad7-e0d5-4652-9fb6-ca8c73d5aa7c.png)

**Comment by XYZliang** [comment]
有更多的报错信息和截图吗？这点报错看不出什么

**Comment by lcqadmin** [comment]
> 还有更多的报错信息和截图吗？

网页打卡，有数字验证码的，如何登陆进行打卡？

**Comment by wsxrfvtgb111** [comment]
![image](https://user-images.githubusercontent.com/75971727/155116731-d73f3b62-ddd9-4b0f-b297-c2feda551578.png)
作者出现了这个错误怎么办？我用腾讯云方法C，是哪个环节出了问题？

**Comment by XYZliang** [comment]
> ![图片](https://user-images.githubusercontent.com/75971727/155116731-d73f3b62-ddd9-4b0f-b297-c2feda551578.png) 作者用腾讯云方法出现了这个错误怎么办？

请另外开启一个issues提问。
连同下方的执行日志一起截图。
最好是在日志查询那截图，有很详细的运行日志。
