### ISSUE TITLE
云服务器运行经常遇到这个错误不能运行，但是删除cookie又能正常运行

### ISSUE THREAD

**Issue by OutlierStar** [XYZliang/AutoZFBXiaoYuanFangYiSign#47]
读取配置文件...
2022-04-02 11:55:00.618489:20201325开始
Traceback (most recent call last):
  File "sign.py", line 501, in <module>
    DoSign()
  File "sign.py", line 484, in DoSign
    return_state = start(int(signID))
  File "sign.py", line 312, in start
    verify_code = verify(cookie)
  File "sign.py", line 137, in verify
    res = opener.open(request)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by XYZliang** [comment]
应该是cookie失效了。大概隔多久不能运行？

**Comment by OutlierStar** [comment]
隔不了多久，应该在一天之内，也许第一次运行之后，第二次就立马失效，问题出现的飘忽不定，但出现的很频繁，我现在都是每天定时清除cookie

**Comment by XYZliang** [comment]
> 隔不了多久，应该在一天之内，也许第一次运行之后，第二次就立马失效，问题出现的飘忽不定，但出现的很频繁，我现在都是每天定时清除cookie

后面我直接就不保存cookie了吧。
