### ISSUE TITLE
多人签到有问题

### ISSUE THREAD

**Issue by xpiaofeng** [XYZliang/AutoZFBXiaoYuanFangYiSign#49]
日志:

START RequestId: 57827fe8-69a5-4ca3-a470-4ddfcf75f566

读取配置文件...

Init Report RequestId: 57827fe8-69a5-4ca3-a470-4ddfcf75f566 Coldstart: 1582ms (PullCode: 557ms InitRuntime: 44ms InitFunction: 981ms) Memory: 128MB MemUsage: 16.51MB

Starting new HTTPS connection (1): worldtimeapi.org:443

https://worldtimeapi.org:443 "GET /api/timezone/Asia/Shanghai HTTP/1.1" 200 None

Starting new HTTPS connection (1): worldtimeapi.org:443

https://worldtimeapi.org:443 "GET /api/timezone/Europe/London HTTP/1.1" 200 None

Starting new HTTPS connection (1): whois.pconline.com.cn:443

https://whois.pconline.com.cn:443 "GET /ip.jsp?ip=175.178.210.11 HTTP/1.1" 200 None

2022-04-13 05:54:15.036335:U2021102141开始

ERROR RequestId: 57827fe8-69a5-4ca3-a470-4ddfcf75f566 Result: Traceback (most recent call last):   File "/var/user/sign.py", line 509, in cloudFun     DoSign()   File "/var/user/sign.py", line 482, in DoSign     return_state = start(int(signID)) ValueError: invalid literal for int() with base 10: 'U2021102141'

END RequestId: 57827fe8-69a5-4ca3-a470-4ddfcf75f566

Report RequestId: 57827fe8-69a5-4ca3-a470-4ddfcf75f566 Duration: 2486ms Memory: 128MB MemUsage: 16.77MB
![1](https://user-images.githubusercontent.com/103556424/163110961-6dd39102-f86b-44d1-80a4-916016338ceb.png)

**Comment by XYZliang** [comment]
一个无关仅要的获取时间api出问题，你的服务器请求不到。原本是用在GitHubAction上的，后面我会更新删掉这个
