### ISSUE TITLE
腾讯云函数 多人签到 只要打卡完了测试就会成功 如果没打卡测试就会失败 怎么回事

### ISSUE THREAD

**Issue by 167lsy** [XYZliang/AutoZFBXiaoYuanFangYiSign#62]
START RequestId: 04f7029f-1acf-4254-9d6f-d9449bc36cb5

Init Report RequestId: 04f7029f-1acf-4254-9d6f-d9449bc36cb5 Coldstart: 632ms (PullCode: 111ms InitRuntime: 6ms InitFunction: 515ms) Memory: 128MB MemUsage: 16.43MB

Starting new HTTPS connection (1): worldtimeapi.org:443

https://worldtimeapi.org:443 "GET /api/timezone/Asia/Shanghai HTTP/1.1" 200 None

Starting new HTTPS connection (1): worldtimeapi.org:443

https://worldtimeapi.org:443 "GET /api/timezone/Europe/London HTTP/1.1" 200 None

Starting new HTTPS connection (1): whois.pconline.com.cn:443

https://whois.pconline.com.cn:443 "GET /ip.jsp?ip=114.132.227.211 HTTP/1.1" 200 None

2022-06-08 16:30:30.739291:21041517开始

登陆数据文件丢失或不存在，尝试重新获取登陆数据

xxx检测成功！

xxx检测成功！

登陆数据检测成功

开始签到

Starting new HTTP connection (1): api.map.baidu.com:80

http://api.map.baidu.com:80 "GET /reverse_geocoding/v3/?ak=80smLnoLWKC9ZZWNLL6i7boKiQeVNEbq&output=json&coordtype=wgs84ll&location=28.657223,115.834798 HTTP/1.1" 200 75

utf-8  confidence = 0.99

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

windows-1251 Russian confidence = 0.01

KOI8-R Russian confidence = 0.01

ISO-8859-5 Russian confidence = 0.0

MacCyrillic Russian confidence = 0.055464480035005766

IBM866 Russian confidence = 0.1568970402975349

IBM855 Russian confidence = 0.14221661547437375

ISO-8859-7 Greek confidence = 0.0

windows-1253 Greek confidence = 0.0

ISO-8859-5 Bulgairan confidence = 0.0

windows-1251 Bulgarian confidence = 0.01

TIS-620 Thai confidence = 0.09745157825979427

ISO-8859-9 Turkish confidence = 0.2989187057698601

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.0

utf-8  confidence = 0.99

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

utf-8  confidence = 0.99

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

windows-1251 Russian confidence = 0.01

KOI8-R Russian confidence = 0.01

ISO-8859-5 Russian confidence = 0.0

MacCyrillic Russian confidence = 0.055464480035005766

IBM866 Russian confidence = 0.1568970402975349

IBM855 Russian confidence = 0.14221661547437375

ISO-8859-7 Greek confidence = 0.0

windows-1253 Greek confidence = 0.0

ISO-8859-5 Bulgairan confidence = 0.0

windows-1251 Bulgarian confidence = 0.01

TIS-620 Thai confidence = 0.09745157825979427

ISO-8859-9 Turkish confidence = 0.2989187057698601

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.0

utf-8  confidence = 0.99

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

ERROR RequestId: 04f7029f-1acf-4254-9d6f-d9449bc36cb5 Result: Traceback (most recent call last):   File "/var/user/sign.py", line 509, in cloudFun     DoSign()   File "/var/user/sign.py", line 482, in DoSign     return_state = start(int(signID))   File "/var/user/sign.py", line 321, in start     sign(cookie=cookie)   File "/var/user/sign.py", line 274, in sign     sign_history(cookie=cookie)   File "/var/user/sign.py", line 171, in sign_history     construction_post(lng, lat, zddlwz)   File "/var/user/sign.py", line 240, in construction_post     add_dic = res_dic['result']['addressComponent'] KeyError: 'result'

END RequestId: 04f7029f-1acf-4254-9d6f-d9449bc36cb5

Report RequestId: 04f7029f-1acf-4254-9d6f-d9449bc36cb5 Duration: 2734ms Memory: 128MB MemUsage: 16.82MB

**Comment by jiangjiangla** [comment]
他原来的百度地图的AK失效了

**Comment by jiangjiangla** [comment]
他原来的百度地图的AK失效了

**Comment by jiangjiangla** [comment]
![image](https://user-images.githubusercontent.com/106958557/172754873-2960171e-6a5a-48e5-a5e3-f129f658845b.png)
这玩意得自己去申请一个
