### ISSUE TITLE
目前腾讯云无法成功运行这个程序了，本地运行可以成功

### ISSUE THREAD

**Issue by YYYHeart** [XYZliang/AutoZFBXiaoYuanFangYiSign#64]
START RequestId: efe7c97b-7d33-4c25-aadf-85385f979cb4Starting new HTTPS connection (1): worldtimeapi.org:443
https://worldtimeapi.org:443 "GET /api/timezone/Asia/Shanghai HTTP/1.1" 200 None
Starting new HTTPS connection (1): worldtimeapi.org:443
https://worldtimeapi.org:443 "GET /api/timezone/Europe/London HTTP/1.1" 200 None
Starting new HTTPS connection (1): whois.pconline.com.cn:443
https://whois.pconline.com.cn:443 "GET /ip.jsp?ip=1.12.247.239 HTTP/1.1" 200 None
2022-06-12 08:36:06.229562:1908211023开始
登陆数据文件丢失或不存在，尝试重新获取登陆数据
ERROR RequestId: efe7c97b-7d33-4c25-aadf-85385f979cb4 Result: Traceback (most recent call last):
  File "/var/lang/python3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/var/lang/python3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/var/lang/python3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/python3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/var/lang/python3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/var/lang/python3/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/var/lang/python3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/var/lang/python3/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/var/lang/python3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/runtime/python3/bootstrap.py", line 176, in handle
    ret = self.real_handler(event, context)
  File "/var/user/sign.py", line 509, in cloudFun
    DoSign()
  File "/var/user/sign.py", line 482, in DoSign
    return_state = start(int(signID))
  File "/var/user/sign.py", line 307, in start
    if login() == 'ERROR':
  File "/var/user/sign.py", line 114, in login
    res = opener.open(request)
  File "/var/lang/python3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/var/lang/python3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/var/lang/python3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/var/lang/python3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/var/lang/python3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>END RequestId: efe7c97b-7d33-4c25-aadf-85385f979cb4Report RequestId: efe7c97b-7d33-4c25-aadf-85385f979cb4 Duration: 136736ms Memory: 128MB MemUsage: 16.89MB

**Comment by YYYHeart** [comment]
我感觉应该是worldtimeapi.org，获取时间ip等这块出问题了

**Comment by YYYHeart** [comment]
现在还会有一个这样的错误
Traceback (most recent call last):
  File "C:\Users\Jason\Desktop\AutoZFBXiaoYuanFangYiSign-main\class2\sign.py", line 499, in <module>
    DoSign()
  File "C:\Users\Jason\Desktop\AutoZFBXiaoYuanFangYiSign-main\class2\sign.py", line 482, in DoSign
    return_state = start(int(signID))
  File "C:\Users\Jason\Desktop\AutoZFBXiaoYuanFangYiSign-main\class2\sign.py", line 310, in start
    verify_code = verify(cookie)
  File "C:\Users\Jason\Desktop\AutoZFBXiaoYuanFangYiSign-main\class2\sign.py", line 135, in verify
    res = opener.open(request)
  File "C:\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
