### ISSUE TITLE
打卡不能正常运行

### ISSUE THREAD

**Issue by xiaqobai** [XYZliang/AutoZFBXiaoYuanFangYiSign#72]
完整问题如下,是因为没有名字嘛?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\AutoZFBXiaoYuanFangYiSign-main\AutoZFBXiaoYuanFangYiSign-main\sign.py", line 499, in <module>
    DoSign()
  File "C:\Users\Administrator\Desktop\AutoZFBXiaoYuanFangYiSign-main\AutoZFBXiaoYuanFangYiSign-main\sign.py", line 476, in DoSign
    statistics(return_state)
  File "C:\Users\Administrator\Desktop\AutoZFBXiaoYuanFangYiSign-main\AutoZFBXiaoYuanFangYiSign-main\sign.py", line 330, in statistics
    message = message + name + " " + str(ID) + " 打卡错误！\n"
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Man1412** [comment]
这个只是要改一个地方，ID没设置或者是ID类型不对，但最近好像打卡接口改了，打不了

**Comment by XYZliang** [comment]
见https://github.com/XYZliang/AutoZFBXiaoYuanFangYiSign/issues/71#issuecomment-1186825546
